# Generated by Django 3.0.7 on 2020-07-04 01:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('catName', models.CharField(max_length=50)),
                ('catId', models.AutoField(primary_key=True, serialize=False)),
                ('catSeverity', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='L', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='OffenseCat',
            fields=[
                ('offenseCat', models.CharField(max_length=50)),
                ('offenseCatId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('officerBadge', models.CharField(max_length=50)),
                ('officerId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('crimeNumber', models.CharField(max_length=14)),
                ('crimeLocation', models.CharField(max_length=50)),
                ('crimeORI', models.CharField(max_length=14)),
                ('crimeCatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police.Cat')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('caseNumber', models.CharField(max_length=14)),
                ('caseLocation', models.CharField(max_length=50)),
                ('caseOffId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police.OffenseCat')),
                ('caseOfficer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police.Officer')),
            ],
        ),
        migrations.CreateModel(
            name='Arrest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('arrestNumber', models.CharField(max_length=14)),
                ('arrestLocation', models.CharField(max_length=50)),
                ('arrestArrestee', models.CharField(max_length=50)),
                ('arrestBirthDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('arrestArresteeAddr', models.TextField()),
                ('arrestArresteeCity', models.CharField(max_length=20)),
                ('arrestArresteeState', models.CharField(max_length=2)),
                ('arrestArresteeZip', models.CharField(max_length=9)),
                ('arrestArresteeStatus', models.CharField(max_length=14)),
                ('arrestOffId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police.OffenseCat')),
                ('arrestOfficer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police.Officer')),
            ],
        ),
    ]
