# Generated by Django 3.0.7 on 2020-07-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0002_filelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='officerName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='officer',
            name='officerBadge',
            field=models.CharField(max_length=5),
        ),
    ]
