# Generated by Django 3.0.7 on 2020-07-04 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0003_auto_20200704_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrest',
            old_name='arrestOffId',
            new_name='arrestOffenseId',
        ),
        migrations.RenameField(
            model_name='arrest',
            old_name='arrestOfficer',
            new_name='arrestOfficerId',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='caseOffId',
            new_name='caseOffenseId',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='caseOfficer',
            new_name='caseOfficerId',
        ),
    ]
