# Generated by Django 3.0.7 on 2020-07-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0004_auto_20200704_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='catUrgency',
            field=models.IntegerField(default=0),
        ),
    ]
