# Generated by Django 3.0.7 on 2020-07-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0005_cat_caturgency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wMonth', models.IntegerField()),
                ('wDay', models.IntegerField()),
                ('wTempMax', models.IntegerField()),
                ('wTempAvg', models.FloatField()),
                ('wTempMin', models.IntegerField()),
                ('wDewMax', models.IntegerField()),
                ('wDewAvg', models.FloatField()),
                ('wDewMin', models.IntegerField()),
                ('wHumidityMax', models.IntegerField()),
                ('wHumidityAvg', models.FloatField()),
                ('wHumidityMin', models.IntegerField()),
                ('wWindMax', models.IntegerField()),
                ('wWindAvg', models.FloatField()),
                ('wWindMin', models.IntegerField()),
                ('wPressureMax', models.IntegerField()),
                ('wPressureAvg', models.FloatField()),
                ('wPressureMin', models.IntegerField()),
                ('wPrecipitation', models.FloatField()),
            ],
        ),
    ]
