# Generated by Django 3.0.7 on 2020-07-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0007_auto_20200708_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='caseLat',
            field=models.FloatField(default=35.22177),
        ),
        migrations.AddField(
            model_name='case',
            name='caseLong',
            field=models.FloatField(default=-97.44496),
        ),
        migrations.AddField(
            model_name='crime',
            name='crimeLat',
            field=models.FloatField(default=35.22177),
        ),
        migrations.AddField(
            model_name='crime',
            name='crimeLong',
            field=models.FloatField(default=-97.44496),
        ),
    ]
