# Generated by Django 3.0.8 on 2020-07-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0008_auto_20200708_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrest',
            name='arrestLat',
            field=models.FloatField(default=35.22177),
        ),
        migrations.AddField(
            model_name='arrest',
            name='arrestLong',
            field=models.FloatField(default=-97.44496),
        ),
    ]
