# Generated by Django 3.0.8 on 2020-07-11 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0009_auto_20200709_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrest',
            old_name='date_posted',
            new_name='arrestDate',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='date_posted',
            new_name='caseDate',
        ),
        migrations.RenameField(
            model_name='crime',
            old_name='date_posted',
            new_name='crimeDate',
        ),
    ]
