# Generated by Django 3.0.8 on 2020-07-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0010_auto_20200711_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graphdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucketSize', models.IntegerField(default=5)),
                ('startDate', models.DateTimeField(default='2020-06-01 00:00:00')),
                ('endDate', models.DateTimeField(default='2020-07-09 00:00:00')),
                ('startUrg', models.IntegerField(default=0)),
                ('endUrg', models.IntegerField(default=5)),
            ],
        ),
    ]
