# Generated by Django 3.0.8 on 2020-07-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0013_auto_20200726_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='caseFiledate',
            new_name='caseFileDate',
        ),
        migrations.AddField(
            model_name='arrest',
            name='arrestFileDate',
            field=models.DateField(default='2020-06-01'),
        ),
        migrations.AddField(
            model_name='crime',
            name='crimeArrest',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='N', max_length=1),
        ),
    ]
